// <auto-generated />
using System;
using CS4540_PS2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CS4540_PS2.Migrations.School
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CS4540_PS2.Models.CourseInstance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Number");

                    b.Property<string>("Professor");

                    b.Property<string>("ProfessorID");

                    b.Property<string>("Semester");

                    b.HasKey("ID");

                    b.ToTable("CourseInstances");
                });

            modelBuilder.Entity("CS4540_PS2.Models.LearningOutcome", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("courseinstanceID");

                    b.HasKey("ID");

                    b.HasIndex("courseinstanceID");

                    b.ToTable("LearningOutcomes");
                });

            modelBuilder.Entity("CS4540_PS2.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("NoteStudentNoteID");

                    b.Property<int>("StudentNoteID");

                    b.HasKey("StudentID");

                    b.HasIndex("NoteStudentNoteID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CS4540_PS2.Models.StudentNote", b =>
                {
                    b.Property<int>("StudentNoteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Note");

                    b.Property<int>("StudentID");

                    b.HasKey("StudentNoteID");

                    b.ToTable("StudentNotes");
                });

            modelBuilder.Entity("CS4540_PS2.Models.LearningOutcome", b =>
                {
                    b.HasOne("CS4540_PS2.Models.CourseInstance")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("courseinstanceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CS4540_PS2.Models.Student", b =>
                {
                    b.HasOne("CS4540_PS2.Models.StudentNote", "Note")
                        .WithMany()
                        .HasForeignKey("NoteStudentNoteID");
                });
#pragma warning restore 612, 618
        }
    }
}
